/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.12.8
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralwidget;
    QPushButton *pushButton;
    QPushButton *Button3;
    QPushButton *Button4;
    QPushButton *Button5;
    QPushButton *Button6;
    QPushButton *Button7;
    QPushButton *Button8;
    QPushButton *Button11;
    QPushButton *Button21;
    QPushButton *Button31;
    QPushButton *Button41;
    QPushButton *Button51;
    QPushButton *Button9;
    QPushButton *Button10;
    QPushButton *Button12;
    QPushButton *Button13;
    QPushButton *Button14;
    QPushButton *Button15;
    QPushButton *Button16;
    QPushButton *Button17;
    QPushButton *Button18;
    QPushButton *Button19;
    QPushButton *Button20;
    QPushButton *Button22;
    QPushButton *Button23;
    QPushButton *Button24;
    QPushButton *Button25;
    QPushButton *Button26;
    QPushButton *Button27;
    QPushButton *Button28;
    QPushButton *Button29;
    QPushButton *Button30;
    QPushButton *Button39;
    QPushButton *Button40;
    QPushButton *Button34;
    QPushButton *Button35;
    QPushButton *Button38;
    QPushButton *Button36;
    QPushButton *Button37;
    QPushButton *Button49;
    QPushButton *Button50;
    QPushButton *Button44;
    QPushButton *Button45;
    QPushButton *Button48;
    QPushButton *Button46;
    QPushButton *Button47;
    QPushButton *Button59;
    QPushButton *Button60;
    QPushButton *Button54;
    QPushButton *Button55;
    QPushButton *Button58;
    QPushButton *Button56;
    QPushButton *Button57;
    QPushButton *Button32;
    QPushButton *Button33;
    QPushButton *Button42;
    QPushButton *Button43;
    QPushButton *Button52;
    QPushButton *Button53;
    QPushButton *Button2;
    QLabel *label;
    QLabel *label_2;
    QLabel *label_3;
    QPushButton *pushButton_2;
    QPushButton *pushButton_3;
    QTextEdit *P1;
    QTextEdit *P2;
    QLabel *label_4;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(1920, 1080);
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        pushButton = new QPushButton(centralwidget);
        pushButton->setObjectName(QString::fromUtf8("pushButton"));
        pushButton->setGeometry(QRect(240, 70, 101, 101));
        pushButton->setStyleSheet(QString::fromUtf8("background-color: rgb(115, 210, 22);\n"
"background-image: url(:/Images/P1 (0).png);"));
        pushButton->setIconSize(QSize(101, 101));
        Button3 = new QPushButton(centralwidget);
        Button3->setObjectName(QString::fromUtf8("Button3"));
        Button3->setGeometry(QRect(460, 70, 101, 101));
        Button3->setStyleSheet(QString::fromUtf8("background-image: url(:/Images/P1 (0).png);"));
        Button3->setIconSize(QSize(101, 101));
        Button4 = new QPushButton(centralwidget);
        Button4->setObjectName(QString::fromUtf8("Button4"));
        Button4->setGeometry(QRect(570, 70, 101, 101));
        Button4->setStyleSheet(QString::fromUtf8("background-image: url(:/Images/P1 (0).png);"));
        Button4->setIconSize(QSize(101, 101));
        Button5 = new QPushButton(centralwidget);
        Button5->setObjectName(QString::fromUtf8("Button5"));
        Button5->setGeometry(QRect(680, 70, 101, 101));
        Button5->setStyleSheet(QString::fromUtf8("background-image: url(:/Images/P1 (0).png);"));
        Button5->setIconSize(QSize(101, 101));
        Button6 = new QPushButton(centralwidget);
        Button6->setObjectName(QString::fromUtf8("Button6"));
        Button6->setGeometry(QRect(790, 70, 101, 101));
        Button6->setStyleSheet(QString::fromUtf8("background-image: url(:/Images/P1 (0).png);"));
        Button6->setIconSize(QSize(101, 101));
        Button7 = new QPushButton(centralwidget);
        Button7->setObjectName(QString::fromUtf8("Button7"));
        Button7->setGeometry(QRect(900, 70, 101, 101));
        Button7->setStyleSheet(QString::fromUtf8("background-image: url(:/Images/P1 (0).png);"));
        Button7->setIconSize(QSize(101, 101));
        Button8 = new QPushButton(centralwidget);
        Button8->setObjectName(QString::fromUtf8("Button8"));
        Button8->setGeometry(QRect(1010, 70, 101, 101));
        Button8->setStyleSheet(QString::fromUtf8("background-image: url(:/Images/P1 (0).png);"));
        Button8->setIconSize(QSize(101, 101));
        Button11 = new QPushButton(centralwidget);
        Button11->setObjectName(QString::fromUtf8("Button11"));
        Button11->setGeometry(QRect(240, 180, 101, 101));
        Button11->setStyleSheet(QString::fromUtf8("background-image: url(:/Images/P1 (0).png);"));
        Button11->setIconSize(QSize(101, 101));
        Button21 = new QPushButton(centralwidget);
        Button21->setObjectName(QString::fromUtf8("Button21"));
        Button21->setGeometry(QRect(240, 290, 101, 101));
        Button21->setStyleSheet(QString::fromUtf8("background-image: url(:/Images/P1 (0).png);"));
        Button21->setIconSize(QSize(101, 101));
        Button31 = new QPushButton(centralwidget);
        Button31->setObjectName(QString::fromUtf8("Button31"));
        Button31->setGeometry(QRect(240, 400, 101, 101));
        Button31->setStyleSheet(QString::fromUtf8("background-image: url(:/Images/P1 (0).png);"));
        Button31->setIconSize(QSize(101, 101));
        Button41 = new QPushButton(centralwidget);
        Button41->setObjectName(QString::fromUtf8("Button41"));
        Button41->setGeometry(QRect(240, 510, 101, 101));
        Button41->setStyleSheet(QString::fromUtf8("background-image: url(:/Images/P1 (0).png);"));
        Button41->setIconSize(QSize(101, 101));
        Button51 = new QPushButton(centralwidget);
        Button51->setObjectName(QString::fromUtf8("Button51"));
        Button51->setGeometry(QRect(240, 620, 101, 101));
        Button51->setStyleSheet(QString::fromUtf8("background-image: url(:/Images/P1 (0).png);"));
        Button51->setIconSize(QSize(101, 101));
        Button9 = new QPushButton(centralwidget);
        Button9->setObjectName(QString::fromUtf8("Button9"));
        Button9->setGeometry(QRect(1120, 70, 101, 101));
        Button9->setStyleSheet(QString::fromUtf8("background-image: url(:/Images/P1 (0).png);"));
        Button9->setIconSize(QSize(101, 101));
        Button10 = new QPushButton(centralwidget);
        Button10->setObjectName(QString::fromUtf8("Button10"));
        Button10->setGeometry(QRect(1230, 70, 101, 101));
        Button10->setStyleSheet(QString::fromUtf8("background-image: url(:/Images/P1 (0).png);"));
        Button10->setIconSize(QSize(101, 101));
        Button12 = new QPushButton(centralwidget);
        Button12->setObjectName(QString::fromUtf8("Button12"));
        Button12->setGeometry(QRect(350, 180, 101, 101));
        Button12->setStyleSheet(QString::fromUtf8("background-image: url(:/Images/P1 (0).png);"));
        Button12->setIconSize(QSize(101, 101));
        Button13 = new QPushButton(centralwidget);
        Button13->setObjectName(QString::fromUtf8("Button13"));
        Button13->setGeometry(QRect(460, 180, 101, 101));
        Button13->setStyleSheet(QString::fromUtf8("background-image: url(:/Images/P1 (0).png);"));
        Button13->setIconSize(QSize(101, 101));
        Button14 = new QPushButton(centralwidget);
        Button14->setObjectName(QString::fromUtf8("Button14"));
        Button14->setGeometry(QRect(570, 180, 101, 101));
        Button14->setStyleSheet(QString::fromUtf8("background-image: url(:/Images/P1 (0).png);"));
        Button14->setIconSize(QSize(101, 101));
        Button15 = new QPushButton(centralwidget);
        Button15->setObjectName(QString::fromUtf8("Button15"));
        Button15->setGeometry(QRect(680, 180, 101, 101));
        Button15->setStyleSheet(QString::fromUtf8("background-image: url(:/Images/P1 (0).png);"));
        Button15->setIconSize(QSize(101, 101));
        Button16 = new QPushButton(centralwidget);
        Button16->setObjectName(QString::fromUtf8("Button16"));
        Button16->setGeometry(QRect(790, 180, 101, 101));
        Button16->setStyleSheet(QString::fromUtf8("background-image: url(:/Images/P1 (0).png);"));
        Button16->setIconSize(QSize(101, 101));
        Button17 = new QPushButton(centralwidget);
        Button17->setObjectName(QString::fromUtf8("Button17"));
        Button17->setGeometry(QRect(900, 180, 101, 101));
        Button17->setStyleSheet(QString::fromUtf8("background-image: url(:/Images/P1 (0).png);"));
        Button17->setIconSize(QSize(101, 101));
        Button18 = new QPushButton(centralwidget);
        Button18->setObjectName(QString::fromUtf8("Button18"));
        Button18->setGeometry(QRect(1010, 180, 101, 101));
        Button18->setStyleSheet(QString::fromUtf8("background-image: url(:/Images/P1 (0).png);"));
        Button18->setIconSize(QSize(101, 101));
        Button19 = new QPushButton(centralwidget);
        Button19->setObjectName(QString::fromUtf8("Button19"));
        Button19->setGeometry(QRect(1120, 180, 101, 101));
        Button19->setStyleSheet(QString::fromUtf8("background-image: url(:/Images/P1 (0).png);"));
        Button19->setIconSize(QSize(101, 101));
        Button20 = new QPushButton(centralwidget);
        Button20->setObjectName(QString::fromUtf8("Button20"));
        Button20->setGeometry(QRect(1230, 180, 101, 101));
        Button20->setStyleSheet(QString::fromUtf8("background-image: url(:/Images/P1 (0).png);"));
        Button20->setIconSize(QSize(101, 101));
        Button22 = new QPushButton(centralwidget);
        Button22->setObjectName(QString::fromUtf8("Button22"));
        Button22->setGeometry(QRect(900, 290, 101, 101));
        Button22->setStyleSheet(QString::fromUtf8("background-image: url(:/Images/P1 (0).png);"));
        Button22->setIconSize(QSize(101, 101));
        Button23 = new QPushButton(centralwidget);
        Button23->setObjectName(QString::fromUtf8("Button23"));
        Button23->setGeometry(QRect(350, 290, 101, 101));
        Button23->setStyleSheet(QString::fromUtf8("background-image: url(:/Images/P1 (0).png);"));
        Button23->setIconSize(QSize(101, 101));
        Button24 = new QPushButton(centralwidget);
        Button24->setObjectName(QString::fromUtf8("Button24"));
        Button24->setGeometry(QRect(460, 290, 101, 101));
        Button24->setStyleSheet(QString::fromUtf8("background-image: url(:/Images/P1 (0).png);"));
        Button24->setIconSize(QSize(101, 101));
        Button25 = new QPushButton(centralwidget);
        Button25->setObjectName(QString::fromUtf8("Button25"));
        Button25->setGeometry(QRect(570, 290, 101, 101));
        Button25->setStyleSheet(QString::fromUtf8("background-image: url(:/Images/P1 (0).png);"));
        Button25->setIconSize(QSize(101, 101));
        Button26 = new QPushButton(centralwidget);
        Button26->setObjectName(QString::fromUtf8("Button26"));
        Button26->setGeometry(QRect(680, 290, 101, 101));
        Button26->setStyleSheet(QString::fromUtf8("background-image: url(:/Images/P1 (0).png);"));
        Button26->setIconSize(QSize(101, 101));
        Button27 = new QPushButton(centralwidget);
        Button27->setObjectName(QString::fromUtf8("Button27"));
        Button27->setGeometry(QRect(790, 290, 101, 101));
        Button27->setStyleSheet(QString::fromUtf8("background-image: url(:/Images/P1 (0).png);"));
        Button27->setIconSize(QSize(101, 101));
        Button28 = new QPushButton(centralwidget);
        Button28->setObjectName(QString::fromUtf8("Button28"));
        Button28->setGeometry(QRect(1010, 290, 101, 101));
        Button28->setStyleSheet(QString::fromUtf8("background-image: url(:/Images/P1 (0).png);"));
        Button28->setIconSize(QSize(101, 101));
        Button29 = new QPushButton(centralwidget);
        Button29->setObjectName(QString::fromUtf8("Button29"));
        Button29->setGeometry(QRect(1120, 290, 101, 101));
        Button29->setStyleSheet(QString::fromUtf8("background-image: url(:/Images/P1 (0).png);"));
        Button29->setIconSize(QSize(101, 101));
        Button30 = new QPushButton(centralwidget);
        Button30->setObjectName(QString::fromUtf8("Button30"));
        Button30->setGeometry(QRect(1230, 290, 101, 101));
        Button30->setStyleSheet(QString::fromUtf8("background-image: url(:/Images/P1 (0).png);"));
        Button30->setIconSize(QSize(101, 101));
        Button39 = new QPushButton(centralwidget);
        Button39->setObjectName(QString::fromUtf8("Button39"));
        Button39->setGeometry(QRect(1120, 400, 101, 101));
        Button39->setStyleSheet(QString::fromUtf8("background-image: url(:/Images/P1 (0).png);"));
        Button39->setIconSize(QSize(101, 101));
        Button40 = new QPushButton(centralwidget);
        Button40->setObjectName(QString::fromUtf8("Button40"));
        Button40->setGeometry(QRect(1230, 400, 101, 101));
        Button40->setStyleSheet(QString::fromUtf8("background-image: url(:/Images/P1 (0).png);"));
        Button40->setIconSize(QSize(101, 101));
        Button34 = new QPushButton(centralwidget);
        Button34->setObjectName(QString::fromUtf8("Button34"));
        Button34->setGeometry(QRect(570, 400, 101, 101));
        Button34->setStyleSheet(QString::fromUtf8("background-image: url(:/Images/P1 (0).png);"));
        Button34->setIconSize(QSize(101, 101));
        Button35 = new QPushButton(centralwidget);
        Button35->setObjectName(QString::fromUtf8("Button35"));
        Button35->setGeometry(QRect(680, 400, 101, 101));
        Button35->setStyleSheet(QString::fromUtf8("background-image: url(:/Images/P1 (0).png);"));
        Button35->setIconSize(QSize(101, 101));
        Button38 = new QPushButton(centralwidget);
        Button38->setObjectName(QString::fromUtf8("Button38"));
        Button38->setGeometry(QRect(1010, 400, 101, 101));
        Button38->setStyleSheet(QString::fromUtf8("background-image: url(:/Images/P1 (0).png);"));
        Button38->setIconSize(QSize(101, 101));
        Button36 = new QPushButton(centralwidget);
        Button36->setObjectName(QString::fromUtf8("Button36"));
        Button36->setGeometry(QRect(790, 400, 101, 101));
        Button36->setStyleSheet(QString::fromUtf8("background-image: url(:/Images/P1 (0).png);"));
        Button36->setIconSize(QSize(101, 101));
        Button37 = new QPushButton(centralwidget);
        Button37->setObjectName(QString::fromUtf8("Button37"));
        Button37->setGeometry(QRect(900, 400, 101, 101));
        Button37->setStyleSheet(QString::fromUtf8("background-image: url(:/Images/P1 (0).png);"));
        Button37->setIconSize(QSize(101, 101));
        Button49 = new QPushButton(centralwidget);
        Button49->setObjectName(QString::fromUtf8("Button49"));
        Button49->setGeometry(QRect(1120, 510, 101, 101));
        Button49->setStyleSheet(QString::fromUtf8("background-image: url(:/Images/P1 (0).png);"));
        Button49->setIconSize(QSize(101, 101));
        Button50 = new QPushButton(centralwidget);
        Button50->setObjectName(QString::fromUtf8("Button50"));
        Button50->setGeometry(QRect(1230, 510, 101, 101));
        Button50->setStyleSheet(QString::fromUtf8("background-image: url(:/Images/P1 (0).png);"));
        Button50->setIconSize(QSize(101, 101));
        Button44 = new QPushButton(centralwidget);
        Button44->setObjectName(QString::fromUtf8("Button44"));
        Button44->setGeometry(QRect(570, 510, 101, 101));
        Button44->setStyleSheet(QString::fromUtf8("background-image: url(:/Images/P1 (0).png);"));
        Button44->setIconSize(QSize(101, 101));
        Button45 = new QPushButton(centralwidget);
        Button45->setObjectName(QString::fromUtf8("Button45"));
        Button45->setGeometry(QRect(680, 510, 101, 101));
        Button45->setStyleSheet(QString::fromUtf8("background-image: url(:/Images/P1 (0).png);"));
        Button45->setIconSize(QSize(101, 101));
        Button48 = new QPushButton(centralwidget);
        Button48->setObjectName(QString::fromUtf8("Button48"));
        Button48->setGeometry(QRect(1010, 510, 101, 101));
        Button48->setStyleSheet(QString::fromUtf8("background-image: url(:/Images/P1 (0).png);"));
        Button48->setIconSize(QSize(101, 101));
        Button46 = new QPushButton(centralwidget);
        Button46->setObjectName(QString::fromUtf8("Button46"));
        Button46->setGeometry(QRect(790, 510, 101, 101));
        Button46->setStyleSheet(QString::fromUtf8("background-image: url(:/Images/P1 (0).png);"));
        Button46->setIconSize(QSize(101, 101));
        Button47 = new QPushButton(centralwidget);
        Button47->setObjectName(QString::fromUtf8("Button47"));
        Button47->setGeometry(QRect(900, 510, 101, 101));
        Button47->setStyleSheet(QString::fromUtf8("background-image: url(:/Images/P1 (0).png);"));
        Button47->setIconSize(QSize(101, 101));
        Button59 = new QPushButton(centralwidget);
        Button59->setObjectName(QString::fromUtf8("Button59"));
        Button59->setGeometry(QRect(1120, 620, 101, 101));
        Button59->setStyleSheet(QString::fromUtf8("background-image: url(:/Images/P1 (0).png);"));
        Button59->setIconSize(QSize(101, 101));
        Button60 = new QPushButton(centralwidget);
        Button60->setObjectName(QString::fromUtf8("Button60"));
        Button60->setGeometry(QRect(1230, 620, 101, 101));
        Button60->setStyleSheet(QString::fromUtf8("background-image: url(:/Images/P1 (0).png);"));
        Button60->setIconSize(QSize(101, 101));
        Button54 = new QPushButton(centralwidget);
        Button54->setObjectName(QString::fromUtf8("Button54"));
        Button54->setGeometry(QRect(570, 620, 101, 101));
        Button54->setStyleSheet(QString::fromUtf8("background-image: url(:/Images/P1 (0).png);"));
        Button54->setIconSize(QSize(101, 101));
        Button55 = new QPushButton(centralwidget);
        Button55->setObjectName(QString::fromUtf8("Button55"));
        Button55->setGeometry(QRect(680, 620, 101, 101));
        Button55->setStyleSheet(QString::fromUtf8("background-image: url(:/Images/P1 (0).png);"));
        Button55->setIconSize(QSize(101, 101));
        Button58 = new QPushButton(centralwidget);
        Button58->setObjectName(QString::fromUtf8("Button58"));
        Button58->setGeometry(QRect(1010, 620, 101, 101));
        Button58->setStyleSheet(QString::fromUtf8("background-image: url(:/Images/P1 (0).png);"));
        Button58->setIconSize(QSize(101, 101));
        Button56 = new QPushButton(centralwidget);
        Button56->setObjectName(QString::fromUtf8("Button56"));
        Button56->setGeometry(QRect(790, 620, 101, 101));
        Button56->setStyleSheet(QString::fromUtf8("background-image: url(:/Images/P1 (0).png);"));
        Button56->setIconSize(QSize(101, 101));
        Button57 = new QPushButton(centralwidget);
        Button57->setObjectName(QString::fromUtf8("Button57"));
        Button57->setGeometry(QRect(900, 620, 101, 101));
        Button57->setStyleSheet(QString::fromUtf8("background-image: url(:/Images/P1 (0).png);"));
        Button57->setIconSize(QSize(101, 101));
        Button32 = new QPushButton(centralwidget);
        Button32->setObjectName(QString::fromUtf8("Button32"));
        Button32->setGeometry(QRect(350, 400, 101, 101));
        Button32->setStyleSheet(QString::fromUtf8("background-image: url(:/Images/P1 (0).png);"));
        Button32->setIconSize(QSize(101, 101));
        Button33 = new QPushButton(centralwidget);
        Button33->setObjectName(QString::fromUtf8("Button33"));
        Button33->setGeometry(QRect(460, 400, 101, 101));
        Button33->setStyleSheet(QString::fromUtf8("background-image: url(:/Images/P1 (0).png);"));
        Button33->setIconSize(QSize(101, 101));
        Button42 = new QPushButton(centralwidget);
        Button42->setObjectName(QString::fromUtf8("Button42"));
        Button42->setGeometry(QRect(350, 510, 101, 101));
        Button42->setStyleSheet(QString::fromUtf8("background-image: url(:/Images/P1 (0).png);"));
        Button42->setIconSize(QSize(101, 101));
        Button43 = new QPushButton(centralwidget);
        Button43->setObjectName(QString::fromUtf8("Button43"));
        Button43->setGeometry(QRect(460, 510, 101, 101));
        Button43->setStyleSheet(QString::fromUtf8("background-image: url(:/Images/P1 (0).png);"));
        Button43->setIconSize(QSize(101, 101));
        Button52 = new QPushButton(centralwidget);
        Button52->setObjectName(QString::fromUtf8("Button52"));
        Button52->setGeometry(QRect(350, 620, 101, 101));
        Button52->setStyleSheet(QString::fromUtf8("background-image: url(:/Images/P1 (0).png);"));
        Button52->setIconSize(QSize(101, 101));
        Button53 = new QPushButton(centralwidget);
        Button53->setObjectName(QString::fromUtf8("Button53"));
        Button53->setGeometry(QRect(460, 620, 101, 101));
        Button53->setStyleSheet(QString::fromUtf8("background-image: url(:/Images/P1 (0).png);"));
        Button53->setIconSize(QSize(101, 101));
        Button2 = new QPushButton(centralwidget);
        Button2->setObjectName(QString::fromUtf8("Button2"));
        Button2->setGeometry(QRect(350, 70, 101, 101));
        Button2->setStyleSheet(QString::fromUtf8("background-color: rgb(115, 210, 22);\n"
"background-image: url(:/Images/P1 (0).png);"));
        Button2->setIconSize(QSize(101, 101));
        label = new QLabel(centralwidget);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(1460, 50, 131, 41));
        label_2 = new QLabel(centralwidget);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(1390, 100, 67, 17));
        label_3 = new QLabel(centralwidget);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(1390, 160, 67, 17));
        pushButton_2 = new QPushButton(centralwidget);
        pushButton_2->setObjectName(QString::fromUtf8("pushButton_2"));
        pushButton_2->setGeometry(QRect(1590, 90, 89, 25));
        pushButton_3 = new QPushButton(centralwidget);
        pushButton_3->setObjectName(QString::fromUtf8("pushButton_3"));
        pushButton_3->setGeometry(QRect(1600, 150, 89, 25));
        P1 = new QTextEdit(centralwidget);
        P1->setObjectName(QString::fromUtf8("P1"));
        P1->setEnabled(true);
        P1->setGeometry(QRect(1470, 90, 104, 31));
        P2 = new QTextEdit(centralwidget);
        P2->setObjectName(QString::fromUtf8("P2"));
        P2->setGeometry(QRect(1470, 150, 104, 31));
        label_4 = new QLabel(centralwidget);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(1390, 210, 461, 41));
        MainWindow->setCentralWidget(centralwidget);
        statusbar = new QStatusBar(MainWindow);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        MainWindow->setStatusBar(statusbar);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", nullptr));
        pushButton->setText(QString());
        Button3->setText(QString());
        Button4->setText(QString());
        Button5->setText(QString());
        Button6->setText(QString());
        Button7->setText(QString());
        Button8->setText(QString());
        Button11->setText(QString());
        Button21->setText(QString());
        Button31->setText(QString());
        Button41->setText(QString());
        Button51->setText(QString());
        Button9->setText(QString());
        Button10->setText(QString());
        Button12->setText(QString());
        Button13->setText(QString());
        Button14->setText(QString());
        Button15->setText(QString());
        Button16->setText(QString());
        Button17->setText(QString());
        Button18->setText(QString());
        Button19->setText(QString());
        Button20->setText(QString());
        Button22->setText(QString());
        Button23->setText(QString());
        Button24->setText(QString());
        Button25->setText(QString());
        Button26->setText(QString());
        Button27->setText(QString());
        Button28->setText(QString());
        Button29->setText(QString());
        Button30->setText(QString());
        Button39->setText(QString());
        Button40->setText(QString());
        Button34->setText(QString());
        Button35->setText(QString());
        Button38->setText(QString());
        Button36->setText(QString());
        Button37->setText(QString());
        Button49->setText(QString());
        Button50->setText(QString());
        Button44->setText(QString());
        Button45->setText(QString());
        Button48->setText(QString());
        Button46->setText(QString());
        Button47->setText(QString());
        Button59->setText(QString());
        Button60->setText(QString());
        Button54->setText(QString());
        Button55->setText(QString());
        Button58->setText(QString());
        Button56->setText(QString());
        Button57->setText(QString());
        Button32->setText(QString());
        Button33->setText(QString());
        Button42->setText(QString());
        Button43->setText(QString());
        Button52->setText(QString());
        Button53->setText(QString());
        Button2->setText(QString());
        label->setText(QApplication::translate("MainWindow", "Jugadores", nullptr));
        label_2->setText(QApplication::translate("MainWindow", "Player 1", nullptr));
        label_3->setText(QApplication::translate("MainWindow", "Player 2", nullptr));
        pushButton_2->setText(QApplication::translate("MainWindow", "Submit", nullptr));
        pushButton_3->setText(QApplication::translate("MainWindow", "Submit", nullptr));
        label_4->setText(QApplication::translate("MainWindow", "Para poder iniciar hay que ingresar ambos nombres y darle a submit", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
